name: Docker Image CI

on:
  push:
    paths:
      - '**.json'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: aymanarman/syllabus-scheduler-app
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
          
